### ISSUE TITLE
how to   execute the code ? where is the order?

### ISSUE THREAD

**Issue by taopanpan** [kevin-keraudren/CETUS-challenge#1]
I want to reproduce the paper with the code ,and I have some problem with it. can you explain the order to execute the code ?

**Comment by kevin-keraudren** [comment]
Thank you for asking, I added a more detailed README, some code fixes, and uploaded a trained model (https://github.com/kevin-keraudren/CETUS-challenge/commit/8dd9ba9cc38f275ad4b42866d3792bae0729ae1c), let me know how it goes.
